title: The Way Out is In
author: Ishank Chauhan
email: myemail@emailclent.com
description: > # this means to ignore newlines until "baseurl:"
  I am a serial procastinator. I am doing all this to give my brain some brownie points. Cheers!!!

# social links
twitter_username: ishankc
github_username:  ishankc

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
